parameters: {}
environment: {}
packages:
    - name: lifeforce
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: weather-latlong
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: weather-zip
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: echo
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}          
